import{create}from'zustand'
import{persist}from'zustand/middleware'
import{WorkPermitItem,JSAItem,SiteEvaluationItem,TBMItem,PTWGroupItem}from'@/types/ptw'

interface PTWStore{
workPermits:WorkPermitItem[]
jsaList:JSAItem[]
siteEvaluations:SiteEvaluationItem[]
tbmList:TBMItem[]
ptwGroups:PTWGroupItem[]
addWorkPermit:(data:WorkPermitItem)=>void
addJSA:(data:JSAItem)=>void
addSiteEvaluation:(data:SiteEvaluationItem)=>void
addTBM:(data:TBMItem)=>void
addPTWGroup:(data:PTWGroupItem)=>void
updateWorkPermit:(id:number,data:Partial<WorkPermitItem>)=>void
updateJSA:(id:number,data:Partial<JSAItem>)=>void
updateSiteEvaluation:(id:number,data:Partial<SiteEvaluationItem>)=>void
updateTBM:(id:number,data:Partial<TBMItem>)=>void
deleteWorkPermit:(id:number)=>void
deleteJSA:(id:number)=>void
deleteSiteEvaluation:(id:number)=>void
deleteTBM:(id:number)=>void
}

export const usePTWStore=create<PTWStore>()(
persist(
(set)=>({
workPermits:[],
jsaList:[],
siteEvaluations:[],
tbmList:[],
ptwGroups:[],
addWorkPermit:(data)=>set((state)=>({workPermits:[...state.workPermits,data]})),
addJSA:(data)=>set((state)=>({jsaList:[...state.jsaList,data]})),
addSiteEvaluation:(data)=>set((state)=>({siteEvaluations:[...state.siteEvaluations,data]})),
addTBM:(data)=>set((state)=>({tbmList:[...state.tbmList,data]})),
addPTWGroup:(data)=>set((state)=>({ptwGroups:[...state.ptwGroups,data]})),
updateWorkPermit:(id,data)=>set((state)=>({workPermits:state.workPermits.map(item=>item.id===id?{...item,...data}:item)})),
updateJSA:(id,data)=>set((state)=>({jsaList:state.jsaList.map(item=>item.id===id?{...item,...data}:item)})),
updateSiteEvaluation:(id,data)=>set((state)=>({siteEvaluations:state.siteEvaluations.map(item=>item.id===id?{...item,...data}:item)})),
updateTBM:(id,data)=>set((state)=>({tbmList:state.tbmList.map(item=>item.id===id?{...item,...data}:item)})),
deleteWorkPermit:(id)=>set((state)=>({workPermits:state.workPermits.filter(item=>item.id!==id)})),
deleteJSA:(id)=>set((state)=>({jsaList:state.jsaList.filter(item=>item.id!==id)})),
deleteSiteEvaluation:(id)=>set((state)=>({siteEvaluations:state.siteEvaluations.filter(item=>item.id!==id)})),
deleteTBM:(id)=>set((state)=>({tbmList:state.tbmList.filter(item=>item.id!==id)}))
}),
{name:'ptw-storage'}
)
)