import React from "react"
import { FileText, ChevronRight, DownloadCloud, ExternalLink, Image, Maximize2, X } from "lucide-react"
import Pagination from "@/components/common/base/Pagination"
import { useNavigate } from "react-router-dom"

type NoticeItem={id:number;category:"공지사항"|"자료실";title:string;updated:string;uploader:string}
type ManualItem={id:number;title:string;updated:string;category:"중대재해처벌법";file:string;uploader:string}
type RiskPhotoItem={id:number;kind:"아차사고"|"안전보이스"|"TBM"|"위험성평가";uploader:string;updated:string;image:string}
type BoardItem=NoticeItem|ManualItem

const notices:NoticeItem[]=[{id:1,category:"공지사항",title:"2025년 법 개정 안내 및 대응 계획",updated:"2025-09-12",uploader:"박작성"},{id:2,category:"공지사항",title:"안전관리책임자 교육 일정 안내",updated:"2025-09-12",uploader:"김근로"},{id:3,category:"공지사항",title:"산업안전보건위원회 정기회의 결과",updated:"2025-09-11",uploader:"홍안전"},{id:4,category:"공지사항",title:"휴가철 안전사고 예방 지침",updated:"2025-09-09",uploader:"박작성"},{id:5,category:"공지사항",title:"협력업체 안전점검 일정 공지",updated:"2025-09-07",uploader:"김근로"},{id:6,category:"공지사항",title:"비상 대피 훈련 결과 보고",updated:"2025-09-07",uploader:"홍안전"},{id:7,category:"공지사항",title:"추석 연휴 근무자 안전 지침",updated:"2025-09-05",uploader:"박작성"},{id:8,category:"공지사항",title:"9월 정기 시설 안전 점검 안내",updated:"2025-09-02",uploader:"김근로"},{id:9,category:"공지사항",title:"안전 캠페인 참여 독려",updated:"2025-08-29",uploader:"홍안전"},{id:10,category:"공지사항",title:"폭염 대비 근로자 건강 관리 지침",updated:"2025-08-27",uploader:"박작성"}]
const resources:NoticeItem[]=[{id:1,category:"자료실",title:"작업환경 개선 지원 사업 자료",updated:"2025-09-13",uploader:"홍안전"},{id:2,category:"자료실",title:"위험성 평가 가이드라인 PDF",updated:"2025-09-13",uploader:"김근로"},{id:3,category:"자료실",title:"개정 산업안전보건법 요약본",updated:"2025-09-10",uploader:"박작성"},{id:4,category:"자료실",title:"안전교육 교안 PPT 자료",updated:"2025-09-09",uploader:"홍안전"},{id:5,category:"자료실",title:"보호구 착용 지침서",updated:"2025-09-06",uploader:"김근로"},{id:6,category:"자료실",title:"위험물질 관리 매뉴얼",updated:"2025-09-06",uploader:"박작성"},{id:7,category:"자료실",title:"응급조치 매뉴얼 PDF",updated:"2025-09-04",uploader:"김근로"},{id:8,category:"자료실",title:"산업재해 사례 모음집",updated:"2025-08-31",uploader:"홍안전"},{id:9,category:"자료실",title:"근골격계 질환 예방 가이드",updated:"2025-08-28",uploader:"박작성"}]
const manuals:ManualItem[]=[{id:1,title:"중대재해 발생 시 초기 대응 매뉴얼",updated:"2025-09-12",category:"중대재해처벌법",file:"severe_accident_initial_response.pdf",uploader:"김근로"},{id:2,title:"중대재해 예방 관리체계 구축 가이드",updated:"2025-09-11",category:"중대재해처벌법",file:"law_system_guide.docx",uploader:"박작성"},{id:3,title:"경영책임자 의무 이행 체크리스트",updated:"2025-09-11",category:"중대재해처벌법",file:"ceo_duties_checklist.pdf",uploader:"홍안전"},{id:4,title:"중대재해처벌법 교육자료",updated:"2025-09-08",category:"중대재해처벌법",file:"law_training.pdf",uploader:"김근로"},{id:5,title:"중대재해 발생 보고 절차",updated:"2025-09-07",category:"중대재해처벌법",file:"reporting_procedure.pdf",uploader:"박작성"},{id:6,title:"안전보건관리체계 점검표",updated:"2025-09-06",category:"중대재해처벌법",file:"safety_checklist.docx",uploader:"홍안전"},{id:7,title:"하청업체 관리 매뉴얼",updated:"2025-09-03",category:"중대재해처벌법",file:"subcontractor_guide.pdf",uploader:"박작성"},{id:8,title:"재해 발생 후 언론 대응 지침",updated:"2025-09-02",category:"중대재해처벌법",file:"media_response.pdf",uploader:"김근로"},{id:9,title:"사고 조사 절차 매뉴얼",updated:"2025-08-30",category:"중대재해처벌법",file:"accident_investigation.pdf",uploader:"홍안전"},{id:10,title:"중대재해 리스크 평가표",updated:"2025-08-28",category:"중대재해처벌법",file:"risk_eval.xlsx",uploader:"박작성"},{id:11,title:"사내 안전 소통 가이드",updated:"2025-08-26",category:"중대재해처벌법",file:"communication_guide.pdf",uploader:"김근로"},{id:12,title:"비상사태 대응 조직도",updated:"2025-08-24",category:"중대재해처벌법",file:"emergency_orgchart.pdf",uploader:"홍안전"},{id:13,title:"중대재해처벌법 최신 판례집",updated:"2025-08-22",category:"중대재해처벌법",file:"law_cases.pdf",uploader:"박작성"}]
const riskPhotos:RiskPhotoItem[]=[{id:1,kind:"TBM",uploader:"홍길동",updated:"2025-07-15",image:""},{id:2,kind:"안전보이스",uploader:"박근로",updated:"2025-07-14",image:""},{id:3,kind:"아차사고",uploader:"이안전",updated:"2025-07-13",image:""},{id:4,kind:"안전보이스",uploader:"김보호",updated:"2025-07-12",image:""},{id:5,kind:"아차사고",uploader:"최안전",updated:"2025-07-11",image:""},{id:6,kind:"위험성평가",uploader:"박관리",updated:"2025-07-10",image:""},{id:7,kind:"아차사고",uploader:"이점검",updated:"2025-07-09",image:""},{id:8,kind:"위험성평가",uploader:"박관리",updated:"2025-07-08",image:""},{id:9,kind:"아차사고",uploader:"한근로",updated:"2025-07-07",image:""},{id:10,kind:"위험성평가",uploader:"김보건",updated:"2025-07-06",image:""},{id:11,kind:"아차사고",uploader:"강안전",updated:"2025-07-05",image:""},{id:12,kind:"안전보이스",uploader:"박근로",updated:"2025-07-04",image:""},{id:13,kind:"아차사고",uploader:"최근로",updated:"2025-07-03",image:""},{id:14,kind:"안전보이스",uploader:"박예방",updated:"2025-07-02",image:""},{id:15,kind:"아차사고",uploader:"이보건",updated:"2025-07-01",image:""},{id:16,kind:"TBM",uploader:"송관리",updated:"2025-06-30",image:""},{id:17,kind:"TBM",uploader:"장예방",updated:"2025-06-29",image:""},{id:18,kind:"안전보이스",uploader:"조안전",updated:"2025-06-28",image:""}]

function useIsMdUp(){const q="(min-width: 768px)";const[ok,setOk]=React.useState(typeof window!=="undefined"?window.matchMedia(q).matches:false);React.useEffect(()=>{const mql=window.matchMedia(q);const on=(e:MediaQueryListEvent)=>setOk(e.matches);if(mql.addEventListener)mql.addEventListener("change",on);else mql.addListener(on);return()=>{if(mql.removeEventListener)mql.removeEventListener("change",on);else mql.removeListener(on)}},[]);return ok}
function usePagination<T>(items:T[],size:number){const[p,setP]=React.useState(1);const total=Math.max(1,Math.ceil(items.length/size));React.useEffect(()=>{if(p>total)p>total&&setP(total)},[total,p]);const start=(p-1)*size;return{currentPage:p,setCurrentPage:setP,totalPages:total,pageItems:items.slice(start,start+size),start}}

const DashboardNotice:React.FC=()=>{const navigate=useNavigate();const TABS=[{key:"공지사항",match:"공지사항"},{key:"자료실",match:"자료실"},{key:"중대재해처벌법",match:"중대재해"}] as const;const[active,setActive]=React.useState<typeof TABS[number]["key"]>("공지사항");const[viewer,setViewer]=React.useState<{src:string;alt:string}|null>(null);const getData=():BoardItem[]=>active==="공지사항"?notices:active==="자료실"?resources:manuals;const imgPool=["/images/photo1.jpg","/images/photo2.jpg","/images/photo3.jpg","/images/photo4.jpg","/images/photo5.jpg","/images/photo6.jpg","/images/photo7.jpg","/images/photo8.jpg","/images/photo9.jpg","/images/photo10.jpg"];React.useEffect(()=>{const on=(e:KeyboardEvent)=>{if(e.key==="Escape")setViewer(null)};if(viewer)document.addEventListener("keydown",on);return()=>document.removeEventListener("keydown",on)},[viewer]);const kindBadgeClass=()=>"bg-gray-100 text-gray-700 border border-gray-300";const LEFT_PAGE_SIZE=8;const leftItems=getData();const{currentPage:leftPage,setCurrentPage:leftSet,totalPages:leftTotal,pageItems:leftPageItems}=usePagination<BoardItem>(leftItems,LEFT_PAGE_SIZE);React.useEffect(()=>{leftSet(1)},[active]);const isMdUp=useIsMdUp();const rightSize=isMdUp?15:9;const{currentPage:rightPage,setCurrentPage:rightSet,totalPages:rightTotal,pageItems:rightItems,start:rightStart}=usePagination(riskPhotos,rightSize)

return(<section className="grid grid-cols-1 md:grid-cols-2 gap-3 items-stretch">
<div className="bg-white rounded-[16px] shadow-sm border border-[#E0E6EA] p-4 flex flex-col md:h-[600px]">
<div className="flex items-center justify-between mb-3"><div className="flex items-center gap-2"><FileText className="w-4 h-4 text-[#1E3C6B]"/><h3 className="text-sm font-semibold text-gray-800">공지/게시판</h3></div><button onClick={()=>{if(active==="공지사항")navigate("/notice-board/notice");else if(active==="자료실")navigate("/notice-board/resources");else navigate("/notice-board/law")}} className="hidden md:inline-flex items-center gap-1 text-[11px] text-gray-500 hover:text-gray-700"><span>전체보기</span><ChevronRight className="w-3.5 h-3.5"/></button></div>
<div className="flex items-center gap-1.5 text-[12px] mb-2">{TABS.map(t=>{const c=t.key==="공지사항"?notices.length:t.key==="자료실"?resources.length:manuals.length;const a=active===t.key?"bg-[#F3F6FB] border-[#C9D6EE] text-[#1E3C6B]":"bg-white border-[#E5E7EB] text-gray-600";return<button key={t.key} onClick={()=>setActive(t.key)} className={`px-2 py-1 rounded-md border ${a}`}>{t.key}<span className="ml-1 text-[11px] text-gray-400">{c}</span></button>})}</div>
<div className="rounded-xl border border-[#EEF2F6] flex-1 overflow-auto">
<ul className="divide-y divide-gray-100">
{leftPageItems.map(item=>{if((item as any).category==="중대재해처벌법"){const m=item as ManualItem;return(<li key={m.id} className="px-3 py-2"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[13px] font-medium text-gray-900 truncate">{m.title}</div><div className="text-[11px] text-gray-500 mt-0.5">{m.updated}·{m.category}·{m.uploader}</div></div><div className="flex items-center gap-1 shrink-0"><button onClick={()=>navigate(`/manual/${m.id}`)} className="text-[11px] border border-[#C9D6EE] bg-[#F3F6FB] text-[#1E3C6B] px-2 py-1 rounded-md flex items-center gap-1"><ExternalLink size={13}/>보기</button><button className="text-[11px] border border-gray-300 bg-white text-gray-800 px-2 py-1 rounded-md flex items-center gap-1"><DownloadCloud size={13}/>다운로드</button></div></div></li>)}else{const n=item as NoticeItem;return(<li key={n.id} className="px-3 py-2"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="text-[13px] font-medium text-gray-900 truncate">{n.title}</div><div className="text-[11px] text-gray-500 mt-0.5">{n.updated}·{n.category}·{n.uploader}</div></div><div className="flex items-center gap-1 shrink-0"><button onClick={()=>n.category==="공지사항"?navigate(`/notice/${n.id}`):navigate(`/resource/${n.id}`)} className="text-[11px] border border-[#C9D6EE] bg-[#F3F6FB] text-[#1E3C6B] px-2 py-1 rounded-md flex items-center gap-1"><ExternalLink size={13}/>보기</button><button className="text-[11px] border border-gray-300 bg-white text-gray-800 px-2 py-1 rounded-md flex items-center gap-1"><DownloadCloud size={13}/>다운로드</button></div></div></li>)}})}
</ul>
</div>
<div className="mt-3 flex justify-center"><Pagination currentPage={leftPage} totalPages={leftTotal} onPageChange={leftSet}/></div>
</div>

<div className="bg-white rounded-[16px] shadow-sm border border-[#E0E6EA] p-4 flex flex-col md:h-[600px]">
<div className="flex items-center justify-between mb-3">
<div className="flex items-center gap-2"><Image className="w-4 h-4 text-[#1E3C6B]"/><h3 className="text-sm font-semibold text-gray-800">사진게시판</h3></div>
<span className="text-[11px] text-gray-500">총 {riskPhotos.length}건</span>
</div>
<div className="flex-1 overflow-auto">
<div className="grid grid-cols-3 md:grid-cols-5 gap-3">
{rightItems.map((r,i)=>{const img=imgPool[(rightStart+i)%imgPool.length];return(
<div key={r.id} className="relative flex flex-col rounded-lg border border-[#EEF2F6] bg-white hover:shadow-md transition overflow-hidden">
<div className="relative w-full h-24 bg-gray-100">
<img src={img} alt={r.kind} className="w-full h-full object-cover"/>
<button aria-label="이미지 확대" onClick={e=>{e.stopPropagation();setViewer({src:img,alt:r.kind})}} className="absolute right-1 top-1 inline-flex items-center justify-center w-6 h-6 rounded-md bg-black/60 text-white hover:bg-black/70"><Maximize2 size={14}/></button>
</div>
<div className="p-1 flex flex-col">
<span className={`inline-flex w-fit items-center px-1 py-0.5 rounded-md text-[10px] ${kindBadgeClass()}`}>{r.kind}</span>
<div className="text-[10px] md:text-[11px] text-gray-500 mt-0.5 truncate">{r.updated}·{r.uploader}</div>
</div>
</div>
)})}
{riskPhotos.length===0&&(<div className="col-span-full py-6 text-center text-[12px] text-gray-500">등록된 위험접수가 없습니다</div>)}
</div>
</div>
<div className="mt-3 flex justify-center"><Pagination currentPage={rightPage} totalPages={rightTotal} onPageChange={p=>rightSet(Math.min(Math.max(1,p),rightTotal))}/></div>
</div>

{viewer&&(<div role="dialog" aria-modal="true" className="fixed inset-0 z-50"><div className="absolute inset-0 bg-black/70" onClick={()=>setViewer(null)}/><div className="absolute inset-0 flex items-center justify-center p-2"><div className="relative"><img src={viewer.src} alt={viewer.alt} className="max-h-[90vh] max-w-[92vw] object-contain rounded-lg shadow-2xl"/><button aria-label="닫기" onClick={()=>setViewer(null)} className="absolute top-2 right-2 inline-flex items-center justify-center w-8 h-8 rounded-md bg-black/60 text-white hover:bg-black/70"><X size={16}/></button></div></div></div>)}
</section>)}

export default DashboardNotice